import time
num1 = float( input("Введите ваш возвраст: ") )
num2 = float( input("Введите кол.во смертей в кс-2: ") )
print("Обработка...")
time.sleep(1)
ans = (num1 - num2)
ans2 = (num1 + num2)
ans3 = (num1 * num2)
ans4 = (num1 / num2)
print(ans)
print(ans2)
print(ans3)
print(ans4)